// Reads spec/schemas/index.json + every schema file, validates the registry, and emits:
//   sdk/src/schemas.ts              — embedded schemas + registry (so Deno/Node need no JSON imports)
//   spec/generated/ts/types.d.ts    — TypeScript body types via json-schema-to-typescript
//   spec/generated/accountability.md — rendered from x-dtp-transitions
// Run: npm run build (from sdk/)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, "..");
const specRoot = resolve(sdkRoot, "..", "spec");
const schemasRoot = join(specRoot, "schemas");

interface TypeEntry {
  file: string;
  schema_versions: string[];
  writable_by: ("company" | "module")[];
  subject: string;
  default_visibility: string;
  strict: boolean;
}
interface Registry {
  protocol_version: string;
  id_base: string;
  envelope: string;
  event: string;
  common: string[];
  types: Record<string, TypeEntry>;
}

const registry: Registry = JSON.parse(readFileSync(join(schemasRoot, "index.json"), "utf8"));

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith(".schema.json")) out.push(p);
  }
  return out;
}

const allFiles = walk(schemasRoot).map((p) => relative(schemasRoot, p).replace(/\\/g, "/")).sort();
const schemas: Record<string, unknown> = {};
const problems: string[] = [];

for (const rel of allFiles) {
  const text = readFileSync(join(schemasRoot, rel), "utf8");
  let json: Record<string, unknown>;
  try {
    json = JSON.parse(text);
  } catch (e) {
    problems.push(`${rel}: invalid JSON (${(e as Error).message})`);
    continue;
  }
  const expectedId = registry.id_base + rel;
  if (json.$id !== expectedId) problems.push(`${rel}: $id is ${json.$id}, expected ${expectedId}`);
  schemas[rel] = json;
}

// Registry consistency
const referenced = new Set<string>([registry.envelope, registry.event, ...registry.common]);
for (const [type, entry] of Object.entries(registry.types)) {
  referenced.add(entry.file);
  if (!schemas[entry.file]) problems.push(`type ${type}: file ${entry.file} not found`);
  const [ns, name] = type.split(".");
  if (!ns || !name) problems.push(`type ${type}: not <namespace>.<name>`);
  const s = schemas[entry.file] as Record<string, unknown> | undefined;
  if (s && s.title !== type) problems.push(`type ${type}: schema title is ${s.title}`);
  if (s && !("x-dtp-transitions" in s)) problems.push(`type ${type}: missing x-dtp-transitions`);
  if (s && entry.strict && s.additionalProperties !== false) problems.push(`type ${type}: strict but additionalProperties != false`);
}
for (const rel of allFiles) if (!referenced.has(rel)) problems.push(`${rel}: not referenced by index.json`);

if (problems.length) {
  console.error("Schema registry problems:\n  " + problems.join("\n  "));
  process.exit(1);
}

// ---- emit sdk/src/schemas.ts ----
const header = `// GENERATED by sdk/scripts/build-schemas.ts from spec/schemas — do not edit.\n`;
const schemasTs =
  header +
  `export const PROTOCOL_VERSION = ${JSON.stringify(registry.protocol_version)};\n` +
  `export const ID_BASE = ${JSON.stringify(registry.id_base)};\n` +
  `export const REGISTRY = ${JSON.stringify(registry, null, 2)} as const;\n` +
  `export const SCHEMAS: Record<string, Record<string, unknown>> = ${JSON.stringify(schemas, null, 2)};\n` +
  `export type RecordTypeName = keyof typeof REGISTRY["types"];\n`;
writeFileSync(join(sdkRoot, "src", "schemas.ts"), schemasTs);

// ---- emit spec/generated/ts/types.d.ts ----
const genDir = join(specRoot, "generated", "ts");
mkdirSync(genDir, { recursive: true });
let dts = `// GENERATED by sdk/scripts/build-schemas.ts from spec/schemas — do not edit.\n\n`;
const seen = new Set<string>();
for (const [type, entry] of Object.entries(registry.types)) {
  const name = type.split(".").map((p) => p.split("_").map((w) => w[0].toUpperCase() + w.slice(1)).join("")).join("") + "Body";
  const schemaPath = join(schemasRoot, entry.file);
  const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
  delete schema.$id; // let the compiler resolve relative refs from cwd
  const ts = await compile(schema, name, {
    cwd: dirname(schemaPath),
    bannerComment: "",
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    style: { singleQuote: false, semi: true, printWidth: 110 },
  });
  // De-duplicate shared interfaces (Money, Quantity, ...) emitted per file
  for (const block of ts.split(/\n(?=export )/)) {
    const m = block.match(/^export (?:interface|type) (\w+)/);
    const key = m ? m[1] : block;
    if (seen.has(key)) continue;
    seen.add(key);
    dts += block.trimEnd() + "\n\n";
  }
}
writeFileSync(join(genDir, "types.d.ts"), dts);

// ---- emit spec/generated/accountability.md ----
let md = `# Accountability matrix (generated)\n\nWho may create each record type and move it between states. Generated from \`x-dtp-transitions\` in spec/schemas — edit the schemas, not this file.\n\n`;
for (const [type, entry] of Object.entries(registry.types)) {
  const s = schemas[entry.file] as Record<string, any>;
  const t = s["x-dtp-transitions"];
  md += `## \`${type}\`\n\nSubject: \`${entry.subject}\` · default visibility: \`${entry.default_visibility}\` · writable by: ${entry.writable_by.join(", ")}\n\n`;
  if (!t) {
    md += `No status machine; superseding records are governed by the envelope rules only.\n\n`;
    continue;
  }
  md += `Initial status: ${t.initial.status.length ? t.initial.status.map((x: string) => `\`${x}\``).join(", ") : "(none)"} — created by: ${t.initial.by.join(", ")}\n\n`;
  if (t.transitions.length) {
    md += `| From | To | Who | Clock | Note |\n|---|---|---|---|---|\n`;
    for (const tr of t.transitions) {
      const clock = tr.within ? `within ${tr.within}` : tr.after ? `after ${tr.after}` : "";
      md += `| ${tr.from} | ${tr.to} | ${tr.by.join(", ")} | ${clock} | ${tr.trigger ? `trigger: ${tr.trigger}` : ""}${tr.note ? ` ${tr.note}` : ""} |\n`;
    }
    md += `\n`;
  }
}
mkdirSync(join(specRoot, "generated"), { recursive: true });
writeFileSync(join(specRoot, "generated", "accountability.md"), md);

console.log(`ok: ${allFiles.length} schemas, ${Object.keys(registry.types).length} record types → sdk/src/schemas.ts, spec/generated/ts/types.d.ts, spec/generated/accountability.md`);
