import { readFileSync, writeFileSync } from "node:fs";
writeFileSync(new URL("../../supabase/migrations/20260907000000_pbp_v03.sql", import.meta.url),
  "-- Generated by sdk/scripts/build-pbp-migration.ts from spec/v0.3/store.sql.\n" + readFileSync(new URL("../../spec/v0.3/store.sql", import.meta.url), "utf8").replace(/\r\n/g, "\n"));
