const root=document.querySelector('#profile-app');let home,org,workspace,profile,busy=false,generation=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v));
async function api(path,p){const r=await fetch(path,p===undefined?{}:{method:'POST',headers:{'content-type':'application/json','x-demo-csrf':home.csrf},body:JSON.stringify({organization_id:org,demo_persona:home.persona,...p})});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
function frame(body){return `<header class="early-header"><a href="/?org=${encodeURIComponent(org||'')}">← Passport workspace</a><div class="brand"><span class="mark">F</span> Financial Profile</div><select id="profile-company" aria-label="Company">${home.companies.map(c=>`<option value="${c.id}" ${c.id===org?'selected':''}>${esc(c.name)}</option>`).join('')}</select></header><p class="early-note">${esc(home.profiles.find(p=>p.id===home.persona)?.name||'No persona selected')} · Independent read-only module · Fictional data</p>${body}`;}
async function load(){const turn=++generation;try{const nextHome=await api('/api/session');if(turn!==generation)return;home=nextHome;if(!home.persona){root.innerHTML='<h1>Choose a person in Passport first.</h1><a href="/">Open Passport</a>';return;}org=org||new URLSearchParams(location.search).get('org')||home.companies.find(c=>c.name==='Acme Sauce')?.id||home.companies[0]?.id;const company=org,persona=home.persona;const nextWorkspace=await api('/api/workspace',{organization_id:company,demo_persona:persona});if(turn!==generation)return;workspace=nextWorkspace;try{const nextProfile=await api('/api/profile/state',{organization_id:company,demo_persona:persona});if(turn!==generation)return;profile=nextProfile;}catch(e){if(turn!==generation)return;profile=null;root.innerHTML=frame(`<section class="early-panel"><h1>Financial Profile unavailable</h1><p>${esc(e.message)}</p>${workspace.permissions.includes('*')&&!workspace.financial_profile?'<button class="primary" data-action="connect">Connect Financial Profile</button>':'<p>Your company controller manages module and membership access.</p>'}</section>`);return;}
root.innerHTML=frame(`<div class="early-title"><div><div class="eyebrow">${esc(workspace.company.name)} / company evidence</div><h1>Financial Profile</h1><p>Current company view, independent of any financing application.</p></div><button data-action="refresh">Refresh profile</button></div><div class="early-warning">Evidence, not a credit score. External debt and liens are unknown, not cleared. No bank integration is connected.</div><div class="early-grid"><section class="early-panel"><h2>Evidence and coverage</h2><p class="early-note">As of ${esc(new Date(profile.as_of).toLocaleString())}. ${esc(profile.coverage)}</p>${profile.fields.map(f=>`<div class="early-profile"><strong>${esc(f.label)}</strong><span class="badge neutral">${esc(f.status)}</span><p>${esc(f.value)}</p><small>${esc(f.source)}</small></div>`).join('')}</section><aside><section class="early-panel"><h2>Recorded obligations</h2>${profile.obligations.length?profile.obligations.map(o=>`<div class="early-profile"><strong>${esc(o.status.replaceAll('_',' '))}</strong><p>${o.outstanding.currency==='USD'&&/^\d+(\.\d{1,2})?$/.test(o.outstanding.amount)?cash(o.outstanding.amount)+' outstanding':esc(o.outstanding.amount+' '+o.outstanding.currency)+' — excluded from supported USD total; needs reconciliation'}</p><small>Due ${esc(new Date(o.maturity_at).toLocaleDateString())} · ${esc(o.lender_name||'External lender')}</small><details><summary>Record reference</summary><code>${esc(o.record_id)}</code></details></div>`).join(''):'<p>No advances in this authorized PBP view. That does not establish an absence of debt.</p>'}</section><section class="early-panel"><h2>Use in other modules</h2><p>Early Pay can request a dated snapshot with your consent. It does not own or continuously read this profile.</p>${workspace.early_pay?`<a class="primary early-link" href="/early-pay?org=${org}">Open Early Pay</a>`:'<p>Early Pay is not installed in this company.</p>'}<p class="early-note">Existing shared copies have their own recipient, purpose and expiry. Disconnecting this module stops fresh reads, not those copies or your financial obligations.</p>${workspace.permissions.includes('*')?'<button class="danger" data-action="disconnect">Disconnect Financial Profile</button>':''}</section></aside></div>`);
}catch(e){if(turn!==generation)return;root.innerHTML=`<section class="early-panel"><h1>Company access unavailable</h1><p>${esc(e.message)}</p><a href="/">Return to Passport</a></section>`;}}
root.addEventListener('change',e=>{if(e.target.id==='profile-company'){org=e.target.value;root.innerHTML='<p>Checking company permissions…</p>';history.replaceState(null,'','/financial-profile?org='+org);void load();}});
root.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||busy)return;busy=true;b.disabled=true;try{if(b.dataset.action==='disconnect'&&!confirm('Disconnect Financial Profile? Fresh reads will stop. Previously shared snapshots and financing obligations remain; revoke evidence sharing separately in Early Pay.'))return;if(b.dataset.action!=='refresh')await api('/api/profile/'+b.dataset.action,{});await load();}catch(e){document.querySelector('#profile-status').textContent=e.message;}finally{busy=false;b.disabled=false;}});
window.addEventListener('focus',()=>{if(!busy)void load();});void load();
