// GENERATED by sdk/scripts/build-schemas.ts from spec/schemas — do not edit.
export const PROTOCOL_VERSION = "0.2";
export const ID_BASE = "https://dtp.dev/schemas/0.2/";
export const REGISTRY = {
  "$comment": "DTP v0.2 type registry. The store, the SDK build, and the docs all derive from this file. writable_by: which principal kinds may issue the record (company = a company key; module = a module key under a core.grant). subject: which body field names the subject company (self = the record is about the subject itself).",
  "protocol_version": "0.2",
  "id_base": "https://dtp.dev/schemas/0.2/",
  "envelope": "core/envelope.schema.json",
  "event": "core/event.schema.json",
  "common": [
    "common/ids.schema.json",
    "common/money.schema.json",
    "common/quantity.schema.json",
    "common/address.schema.json",
    "common/key.schema.json",
    "common/attestation.schema.json",
    "common/certification_ref.schema.json",
    "common/kyb_ref.schema.json",
    "trade/goods_spec.schema.json",
    "trade/delivery_spec.schema.json",
    "trade/freight_terms.schema.json",
    "trade/pack_structure.schema.json",
    "trade/seller_pricing.schema.json",
    "trade/buyer_pricing.schema.json",
    "trade/finance_terms.schema.json"
  ],
  "types": {
    "core.company": {
      "file": "core/company.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company"
      ],
      "subject": "self",
      "default_visibility": "public",
      "strict": true
    },
    "core.module": {
      "file": "core/module.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "publisher_company_id",
      "default_visibility": "public",
      "strict": true
    },
    "core.grant": {
      "file": "core/grant.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company"
      ],
      "subject": "self",
      "default_visibility": "private",
      "strict": true
    },
    "trade.intent": {
      "file": "trade/intent.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "buyer_company_id",
      "default_visibility": "public",
      "strict": true
    },
    "trade.listing": {
      "file": "trade/listing.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "seller_company_id",
      "default_visibility": "public",
      "strict": true
    },
    "trade.offer": {
      "file": "trade/offer.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "offerer_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "trade.contract": {
      "file": "trade/contract.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "buyer_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "trade.fulfillment": {
      "file": "trade/fulfillment.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "seller_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "trade.settlement": {
      "file": "trade/settlement.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "buyer_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "trade.standing_agreement": {
      "file": "trade/standing_agreement.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "proposer_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "finance.invoice": {
      "file": "finance/invoice.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "seller_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "finance.advance_offer": {
      "file": "finance/advance_offer.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "seller_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "finance.advance": {
      "file": "finance/advance.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "seller_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "finance.settlement_event": {
      "file": "finance/settlement_event.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "from_company_id",
      "default_visibility": "counterparties",
      "strict": true
    },
    "traceability.cte": {
      "file": "traceability/cte.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "actor_company_id",
      "default_visibility": "counterparties",
      "strict": false
    },
    "traceability.coa_anchor": {
      "file": "traceability/coa_anchor.schema.json",
      "schema_versions": [
        "0.2"
      ],
      "writable_by": [
        "company",
        "module"
      ],
      "subject": "company_id",
      "default_visibility": "counterparties",
      "strict": false
    }
  }
} as const;
export const SCHEMAS: Record<string, Record<string, unknown>> = {
  "common/address.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/address.schema.json",
    "title": "Address",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "city",
      "region",
      "country"
    ],
    "properties": {
      "line1": {
        "type": [
          "string",
          "null"
        ]
      },
      "line2": {
        "type": [
          "string",
          "null"
        ]
      },
      "city": {
        "type": "string",
        "minLength": 1
      },
      "region": {
        "type": "string",
        "minLength": 1,
        "description": "State/province code or name."
      },
      "postal_code": {
        "type": [
          "string",
          "null"
        ]
      },
      "country": {
        "$ref": "ids.schema.json#/$defs/CountryCode"
      }
    }
  },
  "common/attestation.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/attestation.schema.json",
    "title": "Attestation",
    "description": "A party's statement inside a record body. The proof is the envelope signature of the record that carried it (referenced by record_id); there is no inner signature.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "company_id",
      "attested_at",
      "record_id"
    ],
    "properties": {
      "company_id": {
        "$ref": "ids.schema.json#/$defs/CompanyId"
      },
      "attested_at": {
        "$ref": "ids.schema.json#/$defs/DateTime"
      },
      "record_id": {
        "$ref": "ids.schema.json#/$defs/RecordId",
        "description": "The record whose envelope signature proves this attestation."
      },
      "notes": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "common/certification_ref.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/certification_ref.schema.json",
    "title": "CertificationRef",
    "description": "A certification claim. Never self-asserted: carries the issuer and a verification URL.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "cert_id",
      "cert_type",
      "issuer",
      "issued_at",
      "status"
    ],
    "properties": {
      "cert_id": {
        "type": "string",
        "minLength": 1
      },
      "cert_type": {
        "type": "string",
        "minLength": 1,
        "description": "e.g. USDA_ORGANIC, GAP, SQF, BRC, HACCP, NON_GMO, FAIR_TRADE, FSMA_COMPLIANT"
      },
      "issuer": {
        "type": "string",
        "minLength": 1
      },
      "issuer_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "issued_at": {
        "$ref": "ids.schema.json#/$defs/DateTime"
      },
      "expires_at": {
        "oneOf": [
          {
            "$ref": "ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "verification_url": {
        "type": [
          "string",
          "null"
        ]
      },
      "status": {
        "type": "string",
        "enum": [
          "active",
          "expired",
          "revoked"
        ]
      }
    }
  },
  "common/ids.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/ids.schema.json",
    "title": "DTP identifier grammars",
    "$defs": {
      "RecordId": {
        "type": "string",
        "description": "Writer-assigned UUID (v4 or v7), lowercase.",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      },
      "CompanyId": {
        "type": "string",
        "description": "Company handle. NEAR account-id grammar so a later on-chain mapping is byte-compatible.",
        "minLength": 2,
        "maxLength": 64,
        "pattern": "^(([a-z0-9]+[-_])*[a-z0-9]+\\.)*([a-z0-9]+[-_])*[a-z0-9]+$"
      },
      "ModuleId": {
        "type": "string",
        "description": "Module slug, unique per store.",
        "pattern": "^[a-z0-9][a-z0-9-]{1,62}$"
      },
      "KeyId": {
        "type": "string",
        "description": "Ed25519 public key, NEAR encoding: ed25519:<base58(32 bytes)>.",
        "pattern": "^ed25519:[1-9A-HJ-NP-Za-km-z]{43,44}$"
      },
      "Signature": {
        "type": "string",
        "description": "Ed25519 signature, NEAR encoding: ed25519:<base58(64 bytes)>.",
        "pattern": "^ed25519:[1-9A-HJ-NP-Za-km-z]{86,88}$"
      },
      "RecordType": {
        "type": "string",
        "description": "<namespace>.<type>",
        "pattern": "^[a-z]+\\.[a-z_]+$"
      },
      "Namespace": {
        "type": "string",
        "pattern": "^[a-z]+$"
      },
      "SchemaVersion": {
        "type": "string",
        "pattern": "^[0-9]+\\.[0-9]+$"
      },
      "DateTime": {
        "type": "string",
        "description": "RFC 3339 UTC. Writers SHOULD include milliseconds and MUST use Z.",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{1,6})?Z$"
      },
      "Date": {
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
      },
      "GLN": {
        "type": "string",
        "description": "GS1 Global Location Number (13 digits).",
        "pattern": "^[0-9]{13}$"
      },
      "GTIN": {
        "type": "string",
        "pattern": "^[0-9]{8}$|^[0-9]{12,14}$"
      },
      "DUNS": {
        "type": "string",
        "pattern": "^[0-9]{9}$"
      },
      "Bps": {
        "type": "integer",
        "description": "Basis points.",
        "minimum": 0,
        "maximum": 1000000
      },
      "CountryCode": {
        "type": "string",
        "pattern": "^[A-Z]{2}$"
      }
    }
  },
  "common/key.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/key.schema.json",
    "title": "Key",
    "description": "A signing key attached to a company or module. Rotation = add a new key, revoke the old one. A revoked key's signatures on records created before revoked_at remain valid.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "key_id",
      "role",
      "status",
      "added_at"
    ],
    "properties": {
      "key_id": {
        "$ref": "ids.schema.json#/$defs/KeyId"
      },
      "role": {
        "type": "string",
        "enum": [
          "root",
          "delegate"
        ],
        "description": "Only root keys may change keys[] or write core.grant."
      },
      "label": {
        "type": [
          "string",
          "null"
        ]
      },
      "status": {
        "type": "string",
        "enum": [
          "active",
          "revoked"
        ]
      },
      "added_at": {
        "$ref": "ids.schema.json#/$defs/DateTime"
      },
      "revoked_at": {
        "oneOf": [
          {
            "$ref": "ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "near_account": {
        "type": [
          "string",
          "null"
        ],
        "description": "NEAR account (or sub-account) this key belongs to, if any."
      }
    }
  },
  "common/kyb_ref.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/kyb_ref.schema.json",
    "title": "KybRef",
    "description": "Know-Your-Business attestation anchoring a company to a legal entity.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "legal_name",
      "jurisdiction",
      "provider",
      "issued_at",
      "status"
    ],
    "properties": {
      "legal_name": {
        "type": "string",
        "minLength": 1
      },
      "tax_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "jurisdiction": {
        "$ref": "ids.schema.json#/$defs/CountryCode"
      },
      "provider": {
        "type": "string",
        "minLength": 1,
        "description": "e.g. stripe_identity, persona, manual, mock"
      },
      "attestation_ref": {
        "type": [
          "string",
          "null"
        ]
      },
      "issued_at": {
        "$ref": "ids.schema.json#/$defs/DateTime"
      },
      "expires_at": {
        "oneOf": [
          {
            "$ref": "ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "status": {
        "type": "string",
        "enum": [
          "pending",
          "verified",
          "expired",
          "revoked"
        ]
      }
    }
  },
  "common/money.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/money.schema.json",
    "title": "Money",
    "description": "Decimal string with up to 6 fractional digits (microdollar precision). Never a JSON number.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "amount",
      "currency"
    ],
    "properties": {
      "amount": {
        "type": "string",
        "pattern": "^-?[0-9]+(\\.[0-9]{1,6})?$"
      },
      "currency": {
        "type": "string",
        "enum": [
          "USD",
          "USDC"
        ]
      }
    }
  },
  "common/quantity.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/common/quantity.schema.json",
    "title": "Quantity",
    "description": "Decimal string with up to 3 fractional digits (milliamount precision) plus a unit.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "amount",
      "unit"
    ],
    "properties": {
      "amount": {
        "type": "string",
        "pattern": "^[0-9]+(\\.[0-9]{1,3})?$"
      },
      "unit": {
        "type": "string",
        "enum": [
          "lb",
          "kg",
          "oz",
          "ton",
          "case",
          "pallet",
          "unit"
        ]
      }
    }
  },
  "core/company.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/core/company.schema.json",
    "title": "core.company",
    "description": "The company spine: identity, locations, keys, and attested credentials. Subject is the company itself. The genesis record MUST be signed by a root key listed in its own keys[] (self-certifying bootstrap). Any superseding record that changes keys[] MUST be signed by a root key.",
    "x-dtp-subject": "self",
    "x-dtp-default-visibility": "public",
    "x-dtp-roles": {},
    "x-dtp-transitions": null,
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "display_name",
      "business_type",
      "jurisdiction",
      "locations",
      "keys"
    ],
    "properties": {
      "display_name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 200
      },
      "legal_name": {
        "type": [
          "string",
          "null"
        ]
      },
      "business_type": {
        "type": "string",
        "enum": [
          "producer",
          "brand",
          "distributor",
          "retailer",
          "cooperative",
          "financer",
          "service_provider",
          "agent",
          "other"
        ]
      },
      "jurisdiction": {
        "$ref": "../common/ids.schema.json#/$defs/CountryCode"
      },
      "locations": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "location_id",
            "address"
          ],
          "properties": {
            "location_id": {
              "type": "string",
              "pattern": "^[a-z0-9][a-z0-9-]{0,62}$"
            },
            "label": {
              "type": [
                "string",
                "null"
              ]
            },
            "address": {
              "$ref": "../common/address.schema.json"
            },
            "gln": {
              "oneOf": [
                {
                  "$ref": "../common/ids.schema.json#/$defs/GLN"
                },
                {
                  "type": "null"
                }
              ]
            },
            "roles": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "ship_from",
                  "ship_to",
                  "bill_to",
                  "plant",
                  "warehouse",
                  "office",
                  "farm"
                ]
              },
              "uniqueItems": true
            }
          }
        }
      },
      "identifiers": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "duns": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/DUNS"
              },
              {
                "type": "null"
              }
            ]
          },
          "tax_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "near_account": {
            "type": [
              "string",
              "null"
            ],
            "description": "On-chain identity, if linked. A link, not the id."
          }
        }
      },
      "keys": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "../common/key.schema.json"
        }
      },
      "kyb": {
        "oneOf": [
          {
            "$ref": "../common/kyb_ref.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "certifications": {
        "type": "array",
        "items": {
          "$ref": "../common/certification_ref.schema.json"
        }
      },
      "fsma_pcqi_on_file": {
        "type": "boolean"
      },
      "facility_allergens": {
        "type": "array",
        "uniqueItems": true,
        "items": {
          "type": "string",
          "enum": [
            "milk",
            "eggs",
            "fish",
            "shellfish",
            "tree_nuts",
            "peanuts",
            "wheat",
            "soybeans",
            "sesame"
          ]
        }
      },
      "data_vault_uri": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "core/envelope.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/core/envelope.schema.json",
    "title": "Record envelope",
    "description": "Every DTP record shares this wrapper. The signature is Ed25519 over the canonical JSON (RFC 8785, integer-only numbers) of the envelope minus `signature`.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "record_id",
      "root_id",
      "type",
      "namespace",
      "schema_version",
      "subject_company_id",
      "counterparty_ids",
      "issuer",
      "visibility",
      "created_at",
      "supersedes",
      "body",
      "signature"
    ],
    "properties": {
      "record_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "root_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId",
        "description": "record_id of the first record in this supersession chain; equals record_id for a genesis record. Bodies cross-reference entities by root_id."
      },
      "type": {
        "$ref": "../common/ids.schema.json#/$defs/RecordType"
      },
      "namespace": {
        "$ref": "../common/ids.schema.json#/$defs/Namespace",
        "description": "Must equal the prefix of `type`."
      },
      "schema_version": {
        "$ref": "../common/ids.schema.json#/$defs/SchemaVersion"
      },
      "subject_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId",
        "description": "Whose cabinet this record lives in."
      },
      "counterparty_ids": {
        "type": "array",
        "items": {
          "$ref": "../common/ids.schema.json#/$defs/CompanyId"
        },
        "uniqueItems": true,
        "description": "Other parties to this record. Required non-empty when visibility is `counterparties`."
      },
      "issuer": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "key_id",
          "company_id",
          "module_id"
        ],
        "properties": {
          "key_id": {
            "$ref": "../common/ids.schema.json#/$defs/KeyId"
          },
          "company_id": {
            "$ref": "../common/ids.schema.json#/$defs/CompanyId",
            "description": "The principal. Must be subject_company_id or a member of counterparty_ids."
          },
          "module_id": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/ModuleId"
              },
              {
                "type": "null"
              }
            ],
            "description": "Set when a module key signs on the company's behalf under a core.grant."
          }
        }
      },
      "visibility": {
        "type": "string",
        "enum": [
          "public",
          "counterparties",
          "granted",
          "private"
        ]
      },
      "created_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime",
        "description": "Writer clock. The store records its own received_at on the event."
      },
      "supersedes": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ],
        "description": "record_id of the current head of the chain this record replaces, or null for a genesis record."
      },
      "body": {
        "type": "object",
        "description": "Validated against the schema registered for (type, schema_version). Integers only; decimals are strings."
      },
      "signature": {
        "$ref": "../common/ids.schema.json#/$defs/Signature"
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "visibility": {
              "const": "counterparties"
            }
          }
        },
        "then": {
          "properties": {
            "counterparty_ids": {
              "minItems": 1
            }
          }
        }
      }
    ]
  },
  "core/event.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/core/event.schema.json",
    "title": "core.event",
    "description": "Exactly one event per accepted record write. Events are store assertions (unsigned); the record is the proof. Cursors are opaque strings ordered per store; delivery is at-least-once and visibility-filtered.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "cursor",
      "event_id",
      "kind",
      "record_id",
      "root_id",
      "type",
      "namespace",
      "schema_version",
      "subject_company_id",
      "counterparty_ids",
      "issuer",
      "visibility",
      "supersedes",
      "status",
      "created_at",
      "recorded_at"
    ],
    "properties": {
      "cursor": {
        "type": "string",
        "minLength": 1
      },
      "event_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "kind": {
        "type": "string",
        "enum": [
          "record_appended"
        ]
      },
      "record_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "root_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "type": {
        "$ref": "../common/ids.schema.json#/$defs/RecordType"
      },
      "namespace": {
        "$ref": "../common/ids.schema.json#/$defs/Namespace"
      },
      "schema_version": {
        "$ref": "../common/ids.schema.json#/$defs/SchemaVersion"
      },
      "subject_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "counterparty_ids": {
        "type": "array",
        "items": {
          "$ref": "../common/ids.schema.json#/$defs/CompanyId"
        }
      },
      "issuer": {
        "$ref": "envelope.schema.json#/properties/issuer"
      },
      "visibility": {
        "type": "string",
        "enum": [
          "public",
          "counterparties",
          "granted",
          "private"
        ]
      },
      "supersedes": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "status": {
        "type": [
          "string",
          "null"
        ],
        "description": "Copied from body.status when the type defines one."
      },
      "created_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "recorded_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      }
    }
  },
  "core/grant.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/core/grant.schema.json",
    "title": "core.grant",
    "description": "A company's permission to a module. Subject is the granting company. MUST be signed by a company root key with issuer.module_id null (modules never write grants). Revocation = a superseding record with status revoked; only the head of the chain counts. `write` implies `read`.",
    "x-dtp-subject": "self",
    "x-dtp-default-visibility": "private",
    "x-dtp-roles": {},
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "active"
        ],
        "by": [
          "subject"
        ]
      },
      "transitions": [
        {
          "from": "active",
          "to": "revoked",
          "by": [
            "subject"
          ]
        },
        {
          "from": "active",
          "to": "active",
          "by": [
            "subject"
          ],
          "note": "scope change"
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "module_id",
      "scopes",
      "status"
    ],
    "properties": {
      "module_id": {
        "$ref": "../common/ids.schema.json#/$defs/ModuleId"
      },
      "scopes": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/$defs/Scope"
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "active",
          "revoked"
        ]
      },
      "expires_at": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "note": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "$defs": {
      "Scope": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "access"
        ],
        "properties": {
          "namespace": {
            "type": "string",
            "pattern": "^([a-z]+|\\*)$",
            "description": "A namespace, or * for all."
          },
          "type": {
            "$ref": "../common/ids.schema.json#/$defs/RecordType"
          },
          "access": {
            "type": "string",
            "enum": [
              "read",
              "write"
            ]
          }
        },
        "oneOf": [
          {
            "required": [
              "namespace"
            ],
            "not": {
              "required": [
                "type"
              ]
            }
          },
          {
            "required": [
              "type"
            ],
            "not": {
              "required": [
                "namespace"
              ]
            }
          }
        ]
      }
    }
  },
  "core/module.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/core/module.schema.json",
    "title": "core.module",
    "description": "A software identity with its own keys. Subject is the publisher company. The genesis record may be signed by a module root key listed in keys[] (self-certifying) or by a publisher root key. requested_scopes is advisory (consent screen); authority comes only from core.grant records.",
    "x-dtp-subject": "publisher_company_id",
    "x-dtp-default-visibility": "public",
    "x-dtp-roles": {},
    "x-dtp-transitions": null,
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "module_id",
      "name",
      "publisher_company_id",
      "keys"
    ],
    "properties": {
      "module_id": {
        "$ref": "../common/ids.schema.json#/$defs/ModuleId"
      },
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 200
      },
      "publisher_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "homepage": {
        "type": [
          "string",
          "null"
        ]
      },
      "keys": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "../common/key.schema.json"
        }
      },
      "requested_scopes": {
        "type": "array",
        "items": {
          "$ref": "grant.schema.json#/$defs/Scope"
        }
      }
    }
  },
  "finance/advance.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/finance/advance.schema.json",
    "title": "finance.advance",
    "description": "A funded advance, created only from an accepted advance_offer. Subject is the seller; the financer is the counterparty and owns every transition, each of which MUST cite settlement events.",
    "x-dtp-subject": "seller_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "seller": "seller_company_id",
      "financer": "financer_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "funded"
        ],
        "by": [
          "financer"
        ]
      },
      "transitions": [
        {
          "from": "funded",
          "to": "partially_repaid",
          "by": [
            "financer"
          ],
          "trigger": "finance.settlement_event"
        },
        {
          "from": "funded",
          "to": "repaid",
          "by": [
            "financer"
          ],
          "trigger": "finance.settlement_event"
        },
        {
          "from": "funded",
          "to": "defaulted",
          "by": [
            "financer"
          ],
          "after": "maturity_at"
        },
        {
          "from": "partially_repaid",
          "to": "repaid",
          "by": [
            "financer"
          ]
        },
        {
          "from": "partially_repaid",
          "to": "defaulted",
          "by": [
            "financer"
          ],
          "after": "maturity_at"
        },
        {
          "from": "defaulted",
          "to": "repaid",
          "by": [
            "financer"
          ]
        },
        {
          "from": "defaulted",
          "to": "written_off",
          "by": [
            "financer"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "advance_offer_id",
      "invoice_id",
      "seller_company_id",
      "financer_company_id",
      "principal",
      "fee",
      "funded_at",
      "funding_event_id",
      "maturity_at",
      "repaid_amount",
      "outstanding",
      "status"
    ],
    "properties": {
      "advance_offer_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "invoice_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "financer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "principal": {
        "$ref": "../common/money.schema.json"
      },
      "fee": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "fee_bps",
          "apr_bps"
        ],
        "properties": {
          "fee_bps": {
            "$ref": "../common/ids.schema.json#/$defs/Bps"
          },
          "apr_bps": {
            "$ref": "../common/ids.schema.json#/$defs/Bps"
          },
          "fixed_fee": {
            "oneOf": [
              {
                "$ref": "../common/money.schema.json"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "funded_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "funding_event_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId",
        "description": "root_id of the finance.settlement_event that funded it"
      },
      "maturity_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "repaid_amount": {
        "$ref": "../common/money.schema.json"
      },
      "outstanding": {
        "$ref": "../common/money.schema.json"
      },
      "repayment_event_ids": {
        "type": "array",
        "items": {
          "$ref": "../common/ids.schema.json#/$defs/RecordId"
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "funded",
          "partially_repaid",
          "repaid",
          "defaulted",
          "written_off"
        ]
      }
    }
  },
  "finance/advance_offer.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/finance/advance_offer.schema.json",
    "title": "finance.advance_offer",
    "description": "A financer's offer to advance cash against an invoice. Subject is the seller; the financer is the counterparty and the issuer (via its module). pricing_basis lists the protocol records the decision was made from — proof that no out-of-band intake was needed.",
    "x-dtp-subject": "seller_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "seller": "seller_company_id",
      "financer": "financer_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "offered"
        ],
        "by": [
          "financer"
        ]
      },
      "transitions": [
        {
          "from": "offered",
          "to": "accepted",
          "by": [
            "seller"
          ]
        },
        {
          "from": "offered",
          "to": "declined",
          "by": [
            "seller"
          ]
        },
        {
          "from": "offered",
          "to": "withdrawn",
          "by": [
            "financer"
          ]
        },
        {
          "from": "offered",
          "to": "expired",
          "by": [
            "seller",
            "financer"
          ],
          "after": "expires_at"
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "invoice_id",
      "seller_company_id",
      "financer_company_id",
      "advance_amount",
      "advance_bps",
      "fee",
      "repayment",
      "recourse",
      "pricing_basis",
      "expires_at",
      "status"
    ],
    "properties": {
      "invoice_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "financer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "advance_amount": {
        "$ref": "../common/money.schema.json"
      },
      "advance_bps": {
        "$ref": "../common/ids.schema.json#/$defs/Bps",
        "description": "advance_amount as bps of invoice total"
      },
      "fee": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "fee_bps",
          "apr_bps"
        ],
        "properties": {
          "fee_bps": {
            "$ref": "../common/ids.schema.json#/$defs/Bps"
          },
          "apr_bps": {
            "$ref": "../common/ids.schema.json#/$defs/Bps"
          },
          "fixed_fee": {
            "oneOf": [
              {
                "$ref": "../common/money.schema.json"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "repayment": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "source",
          "due_at"
        ],
        "properties": {
          "source": {
            "type": "string",
            "enum": [
              "buyer_payment",
              "seller"
            ]
          },
          "due_at": {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          }
        }
      },
      "recourse": {
        "type": "string",
        "enum": [
          "full",
          "limited",
          "none"
        ]
      },
      "pricing_basis": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "record_id",
            "type"
          ],
          "properties": {
            "record_id": {
              "$ref": "../common/ids.schema.json#/$defs/RecordId"
            },
            "type": {
              "$ref": "../common/ids.schema.json#/$defs/RecordType"
            },
            "note": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      },
      "expires_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "status": {
        "type": "string",
        "enum": [
          "offered",
          "accepted",
          "declined",
          "expired",
          "withdrawn"
        ]
      }
    }
  },
  "finance/invoice.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/finance/invoice.schema.json",
    "title": "finance.invoice",
    "description": "A receivable. Subject is the seller (AR); the buyer is the counterparty. Issued by the seller or a module holding finance write from the seller. assigned_to_company_id is set when an advance funds and the receivable is assigned to the financer — the field a factor's lockbox exists to replace.",
    "x-dtp-subject": "seller_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "seller": "seller_company_id",
      "buyer": "buyer_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "draft",
          "issued"
        ],
        "by": [
          "seller"
        ]
      },
      "transitions": [
        {
          "from": "draft",
          "to": "issued",
          "by": [
            "seller"
          ]
        },
        {
          "from": "draft",
          "to": "void",
          "by": [
            "seller"
          ]
        },
        {
          "from": "issued",
          "to": "acknowledged",
          "by": [
            "buyer"
          ],
          "within": "PT48H"
        },
        {
          "from": "issued",
          "to": "disputed",
          "by": [
            "buyer"
          ],
          "within": "PT48H"
        },
        {
          "from": "issued",
          "to": "partially_paid",
          "by": [
            "seller"
          ],
          "trigger": "finance.settlement_event"
        },
        {
          "from": "issued",
          "to": "paid",
          "by": [
            "seller"
          ],
          "trigger": "finance.settlement_event"
        },
        {
          "from": "issued",
          "to": "void",
          "by": [
            "seller"
          ]
        },
        {
          "from": "acknowledged",
          "to": "partially_paid",
          "by": [
            "seller"
          ]
        },
        {
          "from": "acknowledged",
          "to": "paid",
          "by": [
            "seller"
          ]
        },
        {
          "from": "acknowledged",
          "to": "disputed",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "disputed",
          "to": "acknowledged",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "disputed",
          "to": "void",
          "by": [
            "seller"
          ]
        },
        {
          "from": "partially_paid",
          "to": "paid",
          "by": [
            "seller"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "invoice_number",
      "seller_company_id",
      "buyer_company_id",
      "contract_id",
      "line_items",
      "subtotal",
      "deductions",
      "total",
      "issued_at",
      "due_at",
      "payment_terms",
      "status",
      "paid_amount",
      "settlement_event_ids"
    ],
    "properties": {
      "invoice_number": {
        "type": "string",
        "minLength": 1
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "contract_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "fulfillment_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "line_items": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "description",
            "quantity",
            "unit_price",
            "amount"
          ],
          "properties": {
            "description": {
              "type": "string",
              "minLength": 1
            },
            "sku": {
              "type": [
                "string",
                "null"
              ]
            },
            "quantity": {
              "$ref": "../common/quantity.schema.json"
            },
            "unit_price": {
              "$ref": "../common/money.schema.json"
            },
            "amount": {
              "$ref": "../common/money.schema.json"
            }
          }
        }
      },
      "subtotal": {
        "$ref": "../common/money.schema.json"
      },
      "deductions": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "reason",
            "amount"
          ],
          "properties": {
            "reason": {
              "type": "string",
              "minLength": 1
            },
            "amount": {
              "$ref": "../common/money.schema.json"
            }
          }
        }
      },
      "total": {
        "$ref": "../common/money.schema.json"
      },
      "issued_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "due_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "payment_terms": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "net_days",
          "paca_covered"
        ],
        "properties": {
          "net_days": {
            "type": "integer",
            "minimum": 0,
            "maximum": 365
          },
          "paca_covered": {
            "type": "boolean"
          },
          "early_pay_discount_bps": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/Bps"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "draft",
          "issued",
          "acknowledged",
          "disputed",
          "partially_paid",
          "paid",
          "void"
        ]
      },
      "paid_amount": {
        "$ref": "../common/money.schema.json"
      },
      "settlement_event_ids": {
        "type": "array",
        "items": {
          "$ref": "../common/ids.schema.json#/$defs/RecordId"
        }
      },
      "assigned_to_company_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/CompanyId"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "finance/settlement_event.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/finance/settlement_event.schema.json",
    "title": "finance.settlement_event",
    "description": "An immutable money movement. Subject is the payer; the payee is the counterparty. No status: corrections are a compensating event whose `reverses` names this one.",
    "x-dtp-subject": "from_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "payer": "from_company_id",
      "payee": "to_company_id"
    },
    "x-dtp-transitions": {
      "status_field": null,
      "initial": {
        "status": [],
        "by": [
          "payer"
        ]
      },
      "transitions": []
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "kind",
      "from_company_id",
      "to_company_id",
      "amount",
      "occurred_at",
      "rail",
      "references",
      "reverses"
    ],
    "properties": {
      "kind": {
        "type": "string",
        "enum": [
          "buyer_payment",
          "advance_funding",
          "advance_repayment",
          "fee",
          "refund",
          "escrow_release",
          "adjustment"
        ]
      },
      "from_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "to_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "amount": {
        "$ref": "../common/money.schema.json"
      },
      "occurred_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "rail": {
        "type": "string",
        "enum": [
          "mock",
          "ach",
          "wire",
          "card",
          "check",
          "usdc_near"
        ]
      },
      "rail_ref": {
        "type": [
          "string",
          "null"
        ]
      },
      "references": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "invoice_id": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/RecordId"
              },
              {
                "type": "null"
              }
            ]
          },
          "advance_id": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/RecordId"
              },
              {
                "type": "null"
              }
            ]
          },
          "contract_id": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/RecordId"
              },
              {
                "type": "null"
              }
            ]
          },
          "trade_settlement_id": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/RecordId"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "reverses": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "memo": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "traceability/coa_anchor.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/traceability/coa_anchor.schema.json",
    "title": "traceability.coa_anchor",
    "description": "Tamper-evident anchor for an off-chain lot document (Certificate of Analysis etc.) by content hash. Subject is the anchoring company.",
    "x-dtp-subject": "company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "anchor": "company_id"
    },
    "x-dtp-transitions": {
      "status_field": null,
      "initial": {
        "status": [],
        "by": [
          "anchor"
        ]
      },
      "transitions": []
    },
    "type": "object",
    "additionalProperties": true,
    "required": [
      "company_id",
      "lot_id",
      "cert_type",
      "issuer",
      "doc_hash"
    ],
    "properties": {
      "company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "lot_id": {
        "type": "string",
        "minLength": 1
      },
      "cert_type": {
        "type": "string",
        "minLength": 1
      },
      "issuer": {
        "type": "string",
        "minLength": 1
      },
      "doc_hash": {
        "type": "string",
        "description": "SHA-256 hex or IPFS CIDv1",
        "pattern": "^([0-9a-f]{64}|b[a-z2-7]{58,})$"
      },
      "doc_uri_hint": {
        "type": [
          "string",
          "null"
        ]
      },
      "issued_at": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "expires_at": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "traceability/cte.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/traceability/cte.schema.json",
    "title": "traceability.cte",
    "description": "An FSMA 204 Critical Tracking Event keyed by a Traceability Lot Code. Subject is the actor. Loose in v0.2 (additional properties allowed) — this namespace is exercised in a later sprint; an EPCIS 2.0 export mapping is planned.",
    "x-dtp-subject": "actor_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "actor": "actor_company_id"
    },
    "x-dtp-transitions": {
      "status_field": null,
      "initial": {
        "status": [],
        "by": [
          "actor"
        ]
      },
      "transitions": []
    },
    "type": "object",
    "additionalProperties": true,
    "required": [
      "cte_type",
      "lot_id",
      "actor_company_id",
      "quantity",
      "event_date"
    ],
    "properties": {
      "cte_type": {
        "type": "string",
        "enum": [
          "growing",
          "creating",
          "receiving",
          "transforming",
          "shipping"
        ]
      },
      "lot_id": {
        "type": "string",
        "minLength": 1,
        "description": "Traceability Lot Code (opaque in v0.2)."
      },
      "output_lot_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "input_lot_ids": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "actor_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "actor_gln": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/GLN"
          },
          {
            "type": "null"
          }
        ]
      },
      "source_gln": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/GLN"
          },
          {
            "type": "null"
          }
        ]
      },
      "dest_gln": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/GLN"
          },
          {
            "type": "null"
          }
        ]
      },
      "quantity": {
        "$ref": "../common/quantity.schema.json"
      },
      "commodity": {
        "type": [
          "string",
          "null"
        ]
      },
      "variety": {
        "type": [
          "string",
          "null"
        ]
      },
      "event_date": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime",
        "description": "When the physical event happened (the envelope created_at is when it was recorded)."
      },
      "contract_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "notes": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "trade/buyer_pricing.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/buyer_pricing.schema.json",
    "title": "BuyerPricing",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "ceiling_price_per_unit"
    ],
    "properties": {
      "ceiling_price_per_unit": {
        "$ref": "../common/money.schema.json"
      },
      "desired_quantity": {
        "oneOf": [
          {
            "$ref": "../common/quantity.schema.json"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "trade/contract.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/contract.schema.json",
    "title": "trade.contract",
    "description": "Binding record of agreed trade terms. Subject is the buyer (it is the buyer's payable); the seller reads it as a counterparty. Created by whichever party accepted the offer; may also be created directly under a standing agreement or by mutual direct agreement.",
    "x-dtp-subject": "buyer_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "buyer": "buyer_company_id",
      "seller": "seller_company_id",
      "arbitrator": "arbitrator_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "active"
        ],
        "by": [
          "buyer",
          "seller"
        ]
      },
      "transitions": [
        {
          "from": "active",
          "to": "in_fulfillment",
          "by": [
            "seller"
          ],
          "trigger": "trade.fulfillment created"
        },
        {
          "from": "active",
          "to": "cancelled",
          "by": [
            "buyer",
            "seller"
          ],
          "note": "mutual: the other party countersigns by superseding again"
        },
        {
          "from": "in_fulfillment",
          "to": "delivered",
          "by": [
            "buyer"
          ],
          "trigger": "fulfillment complete"
        },
        {
          "from": "in_fulfillment",
          "to": "delivered",
          "by": [
            "seller"
          ],
          "after": "dispute_window_hours past seller attestation",
          "note": "presumed acceptance"
        },
        {
          "from": "in_fulfillment",
          "to": "disputed",
          "by": [
            "buyer"
          ],
          "within": "dispute_window_hours"
        },
        {
          "from": "delivered",
          "to": "settled",
          "by": [
            "buyer"
          ],
          "trigger": "trade.settlement created"
        },
        {
          "from": "disputed",
          "to": "resolved_buyer",
          "by": [
            "arbitrator"
          ],
          "within": "P7D"
        },
        {
          "from": "disputed",
          "to": "resolved_seller",
          "by": [
            "arbitrator"
          ],
          "within": "P7D"
        },
        {
          "from": "resolved_buyer",
          "to": "settled",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "resolved_seller",
          "to": "settled",
          "by": [
            "buyer"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "buyer_company_id",
      "seller_company_id",
      "goods",
      "delivery",
      "price_per_unit",
      "total_value",
      "dispute_window_hours",
      "status"
    ],
    "properties": {
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "intent_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "listing_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "offer_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "standing_agreement_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "lot_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "buyer_po_number": {
        "type": [
          "string",
          "null"
        ]
      },
      "goods": {
        "$ref": "goods_spec.schema.json"
      },
      "delivery": {
        "$ref": "delivery_spec.schema.json"
      },
      "finance": {
        "oneOf": [
          {
            "$ref": "finance_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "freight": {
        "oneOf": [
          {
            "$ref": "freight_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "price_per_unit": {
        "$ref": "../common/money.schema.json"
      },
      "total_value": {
        "$ref": "../common/money.schema.json"
      },
      "escrow_ref": {
        "type": [
          "string",
          "null"
        ],
        "description": "On-chain escrow reference; null off-chain."
      },
      "dispute_window_hours": {
        "type": "integer",
        "minimum": 0,
        "default": 48
      },
      "arbitrator_company_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/CompanyId"
          },
          {
            "type": "null"
          }
        ]
      },
      "status": {
        "type": "string",
        "enum": [
          "active",
          "in_fulfillment",
          "delivered",
          "settled",
          "disputed",
          "resolved_buyer",
          "resolved_seller",
          "cancelled"
        ]
      }
    }
  },
  "trade/delivery_spec.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/delivery_spec.schema.json",
    "title": "DeliverySpec",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "destination",
      "window",
      "method"
    ],
    "properties": {
      "destination": {
        "$ref": "../common/address.schema.json"
      },
      "destination_gln": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/GLN"
          },
          {
            "type": "null"
          }
        ]
      },
      "window": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "earliest",
          "latest"
        ],
        "properties": {
          "earliest": {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          "latest": {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          }
        }
      },
      "method": {
        "type": "string",
        "enum": [
          "delivered",
          "fob_origin",
          "third_party_logistics"
        ]
      },
      "temperature_requirements": {
        "oneOf": [
          {
            "type": "string",
            "enum": [
              "ambient",
              "refrigerated",
              "frozen"
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "notes": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "trade/finance_terms.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/finance_terms.schema.json",
    "title": "FinanceTerms",
    "description": "Payment timing and financing mode agreed for a trade. Policy defaults (LP APR, maturity caps, PACA 30-day cliff) are documented in SPEC.md §7 and are not schema-enforced.",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "payment_timing",
      "net_days",
      "paca_covered",
      "financing_mode"
    ],
    "properties": {
      "payment_timing": {
        "type": "string",
        "enum": [
          "delivery_attestation",
          "inspection_period_end"
        ]
      },
      "net_days": {
        "type": "integer",
        "minimum": 0,
        "maximum": 365
      },
      "paca_covered": {
        "type": "boolean"
      },
      "financing_mode": {
        "type": "string",
        "enum": [
          "escrow_only",
          "lp_pool",
          "open_account"
        ]
      },
      "liquidity_pool_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "financer_company_id": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/CompanyId"
          },
          {
            "type": "null"
          }
        ]
      },
      "finance_fee_bps": {
        "$ref": "../common/ids.schema.json#/$defs/Bps"
      }
    }
  },
  "trade/freight_terms.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/freight_terms.schema.json",
    "title": "FreightTerms",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "payer",
      "estimated_freight",
      "quote_source",
      "quoted_at",
      "booked_at_contract"
    ],
    "properties": {
      "payer": {
        "type": "string",
        "enum": [
          "buyer",
          "seller"
        ]
      },
      "estimated_freight": {
        "$ref": "../common/money.schema.json"
      },
      "freight_allowance": {
        "oneOf": [
          {
            "$ref": "../common/money.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "quote_source": {
        "type": "string",
        "enum": [
          "project44",
          "manual_estimate",
          "carrier_quote"
        ]
      },
      "quote_ref": {
        "type": [
          "string",
          "null"
        ]
      },
      "quoted_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "quote_expires_at": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          {
            "type": "null"
          }
        ]
      },
      "booked_at_contract": {
        "type": "boolean"
      }
    }
  },
  "trade/fulfillment.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/fulfillment.schema.json",
    "title": "trade.fulfillment",
    "description": "Delivery record for a contract. Subject is the seller (who attests shipment/delivery); the buyer attests receipt by superseding this record with buyer_attestation filled in. Structured evidence (BOL, temperature logs, inspection) may be attached under x_evidence in v0.2; a first-class evidence type is a v0.3 candidate.",
    "x-dtp-subject": "seller_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "seller": "seller_company_id",
      "buyer": "buyer_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "seller_attested"
        ],
        "by": [
          "seller"
        ]
      },
      "transitions": [
        {
          "from": "seller_attested",
          "to": "buyer_attested",
          "by": [
            "buyer"
          ],
          "within": "contract.dispute_window_hours"
        },
        {
          "from": "seller_attested",
          "to": "disputed",
          "by": [
            "buyer"
          ],
          "within": "contract.dispute_window_hours"
        },
        {
          "from": "seller_attested",
          "to": "complete",
          "by": [
            "seller"
          ],
          "after": "contract.dispute_window_hours",
          "note": "presumed acceptance"
        },
        {
          "from": "buyer_attested",
          "to": "complete",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "disputed",
          "to": "complete",
          "by": [
            "buyer",
            "seller"
          ],
          "note": "after arbitration recorded on the contract"
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "contract_id",
      "seller_company_id",
      "buyer_company_id",
      "delivered_at",
      "quantity_delivered",
      "seller_attestation",
      "buyer_attestation",
      "status"
    ],
    "properties": {
      "contract_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "delivered_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "quantity_delivered": {
        "$ref": "../common/quantity.schema.json"
      },
      "seller_attestation": {
        "$ref": "../common/attestation.schema.json"
      },
      "buyer_attestation": {
        "oneOf": [
          {
            "$ref": "../common/attestation.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "deductions": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "reason",
            "amount"
          ],
          "properties": {
            "reason": {
              "type": "string",
              "minLength": 1
            },
            "amount": {
              "$ref": "../common/money.schema.json"
            }
          }
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "seller_attested",
          "buyer_attested",
          "complete",
          "disputed"
        ]
      }
    }
  },
  "trade/goods_spec.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/goods_spec.schema.json",
    "title": "GoodsSpec",
    "description": "Describes goods requested or offered. Only the *_details block matching product_type is required.",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "category",
      "product_name",
      "product_type",
      "quantity"
    ],
    "properties": {
      "category": {
        "type": "string",
        "minLength": 1,
        "description": "Dotted taxonomy, e.g. condiments.hot_sauce"
      },
      "product_name": {
        "type": "string",
        "minLength": 1
      },
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "product_type": {
        "type": "string",
        "enum": [
          "commodity",
          "branded",
          "value_added"
        ]
      },
      "commodity_details": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": false,
        "properties": {
          "country_of_origin": {
            "$ref": "../common/ids.schema.json#/$defs/CountryCode"
          },
          "farming_practices": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "grade": {
            "type": [
              "string",
              "null"
            ]
          },
          "harvest_date": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/Date"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      },
      "branded_details": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": false,
        "required": [
          "brand_name",
          "sku"
        ],
        "properties": {
          "brand_name": {
            "type": "string",
            "minLength": 1
          },
          "sku": {
            "type": "string",
            "minLength": 1
          },
          "gtin": {
            "oneOf": [
              {
                "$ref": "../common/ids.schema.json#/$defs/GTIN"
              },
              {
                "type": "null"
              }
            ]
          },
          "upc": {
            "type": [
              "string",
              "null"
            ]
          },
          "manufacturer": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      },
      "value_added_details": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": false,
        "required": [
          "process_type"
        ],
        "properties": {
          "process_type": {
            "type": "string",
            "minLength": 1
          },
          "base_ingredients": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "processing_facility": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      },
      "quantity": {
        "$ref": "../common/quantity.schema.json"
      },
      "quality": {
        "type": [
          "object",
          "null"
        ],
        "additionalProperties": false,
        "properties": {
          "grade": {
            "type": [
              "string",
              "null"
            ]
          },
          "specifications": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "required_certifications": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "packaging": {
        "type": [
          "string",
          "null"
        ]
      },
      "shelf_life_days": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 0
      }
    }
  },
  "trade/intent.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/intent.schema.json",
    "title": "trade.intent",
    "description": "A buyer's declaration of what it wants to purchase. Subject is the buyer.",
    "x-dtp-subject": "buyer_company_id",
    "x-dtp-default-visibility": "public",
    "x-dtp-roles": {
      "buyer": "buyer_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "draft",
          "posted"
        ],
        "by": [
          "buyer"
        ]
      },
      "transitions": [
        {
          "from": "draft",
          "to": "posted",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "draft",
          "to": "cancelled",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "posted",
          "to": "matched",
          "by": [
            "buyer"
          ],
          "note": "recorded by the buyer (or its matcher module) when a match is accepted for negotiation"
        },
        {
          "from": "posted",
          "to": "cancelled",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "posted",
          "to": "expired",
          "by": [
            "buyer"
          ],
          "after": "expires_at"
        },
        {
          "from": "matched",
          "to": "contracted",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "matched",
          "to": "cancelled",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "contracted",
          "to": "fulfilled",
          "by": [
            "buyer"
          ]
        },
        {
          "from": "fulfilled",
          "to": "settled",
          "by": [
            "buyer"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "buyer_company_id",
      "goods",
      "delivery",
      "pricing",
      "expires_at",
      "status"
    ],
    "properties": {
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "catalog_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "goods": {
        "$ref": "goods_spec.schema.json"
      },
      "delivery": {
        "$ref": "delivery_spec.schema.json"
      },
      "pricing": {
        "$ref": "buyer_pricing.schema.json"
      },
      "finance": {
        "oneOf": [
          {
            "$ref": "finance_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "freight": {
        "oneOf": [
          {
            "$ref": "freight_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "expires_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "status": {
        "type": "string",
        "enum": [
          "draft",
          "posted",
          "matched",
          "contracted",
          "fulfilled",
          "settled",
          "expired",
          "cancelled"
        ]
      }
    }
  },
  "trade/listing.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/listing.schema.json",
    "title": "trade.listing",
    "description": "A seller's proactive broadcast of available supply. Subject is the seller. MOQ lives in pack_structure.",
    "x-dtp-subject": "seller_company_id",
    "x-dtp-default-visibility": "public",
    "x-dtp-roles": {
      "seller": "seller_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "draft",
          "active"
        ],
        "by": [
          "seller"
        ]
      },
      "transitions": [
        {
          "from": "draft",
          "to": "active",
          "by": [
            "seller"
          ]
        },
        {
          "from": "draft",
          "to": "withdrawn",
          "by": [
            "seller"
          ]
        },
        {
          "from": "active",
          "to": "matched",
          "by": [
            "seller"
          ]
        },
        {
          "from": "active",
          "to": "withdrawn",
          "by": [
            "seller"
          ]
        },
        {
          "from": "active",
          "to": "expired",
          "by": [
            "seller"
          ],
          "after": "expires_at"
        },
        {
          "from": "matched",
          "to": "contracted",
          "by": [
            "seller"
          ]
        },
        {
          "from": "matched",
          "to": "withdrawn",
          "by": [
            "seller"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "seller_company_id",
      "goods",
      "pack_structure",
      "delivery",
      "pricing",
      "available_from",
      "expires_at",
      "status"
    ],
    "properties": {
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "lot_id": {
        "type": [
          "string",
          "null"
        ]
      },
      "goods": {
        "$ref": "goods_spec.schema.json"
      },
      "pack_structure": {
        "$ref": "pack_structure.schema.json"
      },
      "delivery": {
        "$ref": "delivery_spec.schema.json"
      },
      "pricing": {
        "$ref": "seller_pricing.schema.json"
      },
      "finance": {
        "oneOf": [
          {
            "$ref": "finance_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "freight": {
        "oneOf": [
          {
            "$ref": "freight_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "certifications": {
        "type": "array",
        "items": {
          "$ref": "../common/certification_ref.schema.json"
        }
      },
      "available_from": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "expires_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "status": {
        "type": "string",
        "enum": [
          "draft",
          "active",
          "matched",
          "contracted",
          "expired",
          "withdrawn"
        ]
      }
    }
  },
  "trade/offer.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/offer.schema.json",
    "title": "trade.offer",
    "description": "A targeted response to a posted intent or listing. Subject is the offerer; the target's owner is the counterparty.",
    "x-dtp-subject": "offerer_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "offerer": "offerer_company_id",
      "target_owner": "target_owner_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "submitted"
        ],
        "by": [
          "offerer"
        ]
      },
      "transitions": [
        {
          "from": "submitted",
          "to": "shortlisted",
          "by": [
            "target_owner"
          ]
        },
        {
          "from": "submitted",
          "to": "accepted",
          "by": [
            "target_owner"
          ]
        },
        {
          "from": "submitted",
          "to": "rejected",
          "by": [
            "target_owner"
          ]
        },
        {
          "from": "submitted",
          "to": "retracted",
          "by": [
            "offerer"
          ]
        },
        {
          "from": "submitted",
          "to": "expired",
          "by": [
            "offerer",
            "target_owner"
          ],
          "after": "expires_at"
        },
        {
          "from": "shortlisted",
          "to": "accepted",
          "by": [
            "target_owner"
          ]
        },
        {
          "from": "shortlisted",
          "to": "rejected",
          "by": [
            "target_owner"
          ]
        },
        {
          "from": "shortlisted",
          "to": "retracted",
          "by": [
            "offerer"
          ]
        },
        {
          "from": "shortlisted",
          "to": "expired",
          "by": [
            "offerer",
            "target_owner"
          ],
          "after": "expires_at"
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "offerer_company_id",
      "target_type",
      "target_id",
      "target_owner_company_id",
      "goods",
      "delivery",
      "price_per_unit",
      "total_price",
      "expires_at",
      "status"
    ],
    "properties": {
      "offerer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "target_type": {
        "type": "string",
        "enum": [
          "intent",
          "listing"
        ]
      },
      "target_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId",
        "description": "root_id of the intent or listing"
      },
      "target_owner_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "goods": {
        "$ref": "goods_spec.schema.json"
      },
      "delivery": {
        "$ref": "delivery_spec.schema.json"
      },
      "finance": {
        "oneOf": [
          {
            "$ref": "finance_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "freight": {
        "oneOf": [
          {
            "$ref": "freight_terms.schema.json"
          },
          {
            "type": "null"
          }
        ]
      },
      "price_per_unit": {
        "$ref": "../common/money.schema.json"
      },
      "total_price": {
        "$ref": "../common/money.schema.json"
      },
      "certifications": {
        "type": "array",
        "items": {
          "$ref": "../common/certification_ref.schema.json"
        }
      },
      "expires_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      },
      "status": {
        "type": "string",
        "enum": [
          "submitted",
          "shortlisted",
          "accepted",
          "rejected",
          "expired",
          "retracted"
        ]
      }
    }
  },
  "trade/pack_structure.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/pack_structure.schema.json",
    "title": "PackStructure",
    "description": "Physical packaging hierarchy. Tier breakpoints are derived from it.",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "unit_size",
      "units_per_case",
      "moq"
    ],
    "properties": {
      "unit_size": {
        "$ref": "../common/quantity.schema.json"
      },
      "units_per_case": {
        "type": "integer",
        "minimum": 1
      },
      "cases_per_pallet": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 1
      },
      "pallets_per_truckload": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 1
      },
      "moq": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "quantity"
        ],
        "properties": {
          "quantity": {
            "$ref": "../common/quantity.schema.json"
          },
          "label": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    }
  },
  "trade/seller_pricing.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/seller_pricing.schema.json",
    "title": "SellerPricing",
    "description": "Published asking price and volume tiers. Floor price is never published; it lives in the seller agent's private context.",
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "model",
      "asking_price_per_unit"
    ],
    "properties": {
      "model": {
        "type": "string",
        "enum": [
          "flat",
          "tiered",
          "negotiable"
        ]
      },
      "asking_price_per_unit": {
        "$ref": "../common/money.schema.json"
      },
      "tiers": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "min_quantity",
            "price_per_unit"
          ],
          "properties": {
            "min_quantity": {
              "$ref": "../common/quantity.schema.json"
            },
            "max_quantity": {
              "oneOf": [
                {
                  "$ref": "../common/quantity.schema.json"
                },
                {
                  "type": "null"
                }
              ]
            },
            "price_per_unit": {
              "$ref": "../common/money.schema.json"
            },
            "label": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    }
  },
  "trade/settlement.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/settlement.schema.json",
    "title": "trade.settlement",
    "description": "Final accounting for a contract. Subject is the buyer (payer); the seller is the counterparty. Terminal: corrections are a new settlement whose `corrects` names this one.",
    "x-dtp-subject": "buyer_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "buyer": "buyer_company_id",
      "seller": "seller_company_id"
    },
    "x-dtp-transitions": {
      "status_field": null,
      "initial": {
        "status": [],
        "by": [
          "buyer"
        ]
      },
      "transitions": []
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "contract_id",
      "fulfillment_id",
      "buyer_company_id",
      "seller_company_id",
      "gross_amount",
      "deductions",
      "net_amount",
      "settled_at"
    ],
    "properties": {
      "contract_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "fulfillment_id": {
        "$ref": "../common/ids.schema.json#/$defs/RecordId"
      },
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "gross_amount": {
        "$ref": "../common/money.schema.json"
      },
      "deductions": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "reason",
            "amount"
          ],
          "properties": {
            "reason": {
              "type": "string",
              "minLength": 1
            },
            "amount": {
              "$ref": "../common/money.schema.json"
            }
          }
        }
      },
      "net_amount": {
        "$ref": "../common/money.schema.json"
      },
      "escrow_release_tx": {
        "type": [
          "string",
          "null"
        ]
      },
      "settlement_event_ids": {
        "type": "array",
        "items": {
          "$ref": "../common/ids.schema.json#/$defs/RecordId"
        },
        "description": "finance.settlement_event root_ids that moved the money."
      },
      "corrects": {
        "oneOf": [
          {
            "$ref": "../common/ids.schema.json#/$defs/RecordId"
          },
          {
            "type": "null"
          }
        ]
      },
      "settled_at": {
        "$ref": "../common/ids.schema.json#/$defs/DateTime"
      }
    }
  },
  "trade/standing_agreement.schema.json": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dtp.dev/schemas/0.2/trade/standing_agreement.schema.json",
    "title": "trade.standing_agreement",
    "description": "A framework governing a series of trades. Subject is the proposer; the other party is the counterparty. Countersignature = the counterparty supersedes the record, appending to signatures[] and setting status active.",
    "x-dtp-subject": "proposer_company_id",
    "x-dtp-default-visibility": "counterparties",
    "x-dtp-roles": {
      "proposer": "proposer_company_id",
      "buyer": "buyer_company_id",
      "seller": "seller_company_id"
    },
    "x-dtp-transitions": {
      "status_field": "status",
      "initial": {
        "status": [
          "proposed"
        ],
        "by": [
          "proposer"
        ]
      },
      "transitions": [
        {
          "from": "proposed",
          "to": "countered",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "proposed",
          "to": "active",
          "by": [
            "buyer",
            "seller"
          ],
          "note": "counterparty countersigns"
        },
        {
          "from": "proposed",
          "to": "terminated",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "countered",
          "to": "active",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "countered",
          "to": "countered",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "countered",
          "to": "terminated",
          "by": [
            "buyer",
            "seller"
          ]
        },
        {
          "from": "active",
          "to": "completed",
          "by": [
            "buyer",
            "seller"
          ],
          "after": "terms.period_end"
        },
        {
          "from": "active",
          "to": "terminated",
          "by": [
            "buyer",
            "seller"
          ]
        }
      ]
    },
    "type": "object",
    "additionalProperties": false,
    "patternProperties": {
      "^x_": {}
    },
    "required": [
      "proposer_company_id",
      "proposer_role",
      "buyer_company_id",
      "seller_company_id",
      "goods",
      "terms",
      "signatures",
      "status"
    ],
    "properties": {
      "proposer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "proposer_role": {
        "type": "string",
        "enum": [
          "buyer",
          "seller"
        ]
      },
      "buyer_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "seller_company_id": {
        "$ref": "../common/ids.schema.json#/$defs/CompanyId"
      },
      "goods": {
        "$ref": "goods_spec.schema.json"
      },
      "terms": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "period_start",
          "period_end",
          "pricing",
          "renewal"
        ],
        "properties": {
          "period_start": {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          "period_end": {
            "$ref": "../common/ids.schema.json#/$defs/DateTime"
          },
          "volume_commitment": {
            "type": [
              "object",
              "null"
            ],
            "additionalProperties": false,
            "properties": {
              "min_quantity_per_period": {
                "$ref": "../common/quantity.schema.json"
              },
              "period": {
                "type": "string",
                "enum": [
                  "monthly",
                  "quarterly",
                  "annual"
                ]
              },
              "committed_total": {
                "$ref": "../common/quantity.schema.json"
              }
            }
          },
          "pricing": {
            "$ref": "seller_pricing.schema.json"
          },
          "delivery_cadence": {
            "type": [
              "string",
              "null"
            ]
          },
          "renewal": {
            "type": "string",
            "enum": [
              "auto",
              "manual",
              "none"
            ]
          }
        }
      },
      "signatures": {
        "type": "array",
        "items": {
          "$ref": "../common/attestation.schema.json"
        }
      },
      "status": {
        "type": "string",
        "enum": [
          "proposed",
          "countered",
          "active",
          "completed",
          "terminated"
        ]
      }
    }
  }
};
export type RecordTypeName = keyof typeof REGISTRY["types"];
